CI test failed

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -35,6 +35,12 @@ jobs:
       - name: Install dependencies
         run: pnpm install --frozen-lockfile
       - name: Check steps
-        run: | 
+        run: |
           export DRY_RUN=true; 
-          pnpm bun:test -- --dry-run 1>&2 | if grep -q -e "undefined" -e "ambiguous"; then exit 1; else exit 0; fi
+          if pnpm bun:test -- --dry-run 2>&1 | grep -q -e "undefined" -e "ambiguous"; then 
+            echo "Error: Found 'undefined' or 'ambiguous' in the output."
+            exit 1
+          else 
+            echo "Success: No 'undefined' or 'ambiguous' found."
+            exit 0
+          fi
