add step to discover tenant-process pod ip address in qa workflow

diff --git a/.github/workflows/qa.yaml b/.github/workflows/qa.yaml
--- a/.github/workflows/qa.yaml
+++ b/.github/workflows/qa.yaml
@@ -525,6 +525,26 @@ jobs:
       ST_VERBOSE_MODE: ${{ vars.ST_VERBOSE_MODE }}
 
     steps:
+      - name: Discover tenant-process pod IP address
+        id: discover_tenant_process_pod_ip_address
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          echo "Discovering tenant-process pod IP address..."
+
+          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
+
+          TENANT_PROCESS_POD_IP=$(kubectl get pods -n ${{ vars.K8S_NAMESPACE }} -l app.kubernetes.io/name=interop-be-tenant-process -o jsonpath='{.items[0].status.podIP}')
+
+          if [[ -z "$TENANT_PROCESS_POD_IP" ]]; then
+            echo "Unable to discover tenant-process pod IP address"
+            exit 1
+          fi
+
+          echo "Successfully discovered the tenant-process pod IP address: $TENANT_PROCESS_POD_IP"
+          echo "TENANT_PROCESS_POD_IP=$TENANT_PROCESS_POD_IP" >> "$GITHUB_ENV"
+
       - name: Set up Maven
         uses: s4u/setup-maven-action@6d44c18d67d9e1549907b8815efa5e4dada1801b # v1.12.0
         with:
